version: '3.8'

services:
  py-arel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py-arel
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
